services:
  onboard:
    image: ricojia/mumble_onboard:latest
    pull_policy: if_not_present
    build:
      context: ./mumble_onboard
      dockerfile: ${CURRENT_DIR}/Dockerfile_mumble_onboard
    container_name: mumble_onboard_container
    command: /bin/bash
    stdin_open: true
    tty: true
    profiles:
      - amd
    volumes:
      - ${CURRENT_DIR}:/home/mumble_robot/src/mumble_onboard # Mount current directory
      - ${CURRENT_DIR}/../mumble_interfaces:/home/mumble_robot/src/mumble_interfaces # Mount current directory
      # Change me if needed
      - /home/ricojia/file_exchange_port/Deep-Blue-Academy-SLAM/slam_in_autonomous_driving/data/:/home/mumble_robot/data/
      - /dev/shm:/dev/shm # when net=host, sharedmemory is used for communication
    network_mode: host  # Use host network mode so topics can be heard