services:
  rpi_runtime:
    image: ricojia/mumble_physical_runtime_rpi:latest  # Use this tag if available
    pull_policy: always  # Always pull the latest image
    container_name: mumble_physical_runtime_container
    command: /bin/bash
    stdin_open: true  # Keep stdin open to allow interactive mode, docker run -i
    tty: true         # Allocate a pseudo-TTY, docker run -t
    profiles:
      - arm
    volumes:
      - ${CURRENT_DIR}/mumble_physical_runtime:/home/mumble_physical_runtime/src  # Mount current directory
    devices:
      - "/dev/serial0:/dev/serial0"  # Bind the entire /dev directory
      - "/dev/serial1:/dev/serial1"  # Bind the entire /dev directory
      - /dev/shm:/dev/shm # when net=host, sharedmemory is used for communication
    environment:
      - WORKDIRECTORY=/home/mumble_physical_runtime
    privileged: true  # Enable privileged mode for full device access
    network_mode: host  # Use host network mode so topics can be heard

  # This needs to be removed if we have a simulation runtime. This is a mirror of rpi
  test_runtime:
    image: ricojia/mumble_physical_runtime:latest
    pull_policy: if_not_present
    build:
      context: ./mumble_physical_runtime
      dockerfile: Dockerfile_mumble_physical_runtime
      args:
        - WORKDIRECTORY=/home/mumble_robot
        - PACKAGE_DIR=/home/mumble_robot/src/mumble_physical_runtime
    container_name: mumble_physical_runtime_container
    command: /bin/bash
    stdin_open: true
    tty: true
    profiles:
      - amd
    volumes:
      - ${CURRENT_DIR}/mumble_physical_runtime:/home/mumble_robot/src/mumble_physical_runtime # Mount current directory
      - ${CURRENT_DIR}/mumble_interfaces:/home/mumble_robot/src/mumble_interfaces # Mount current directory
      - /dev/shm:/dev/shm # when net=host, sharedmemory is used for communication
    network_mode: host  # Use host network mode so topics can be heard
