# DOCKER_BUILDKIT=1 docker build -f Dockerfile_mumble_physical_runtime -t mumble_physical_runtime .
# DOCKER_BUILDKIT=1 docker build --platform linux/arm64/v8 -f Dockerfile_mumble_physical_runtime -t mumble_physical_runtime_rpi .
# FROM ros:humble-ros-core  # This did not work with apt-get
FROM osrf/ros:humble-desktop

ENV DEBIAN_FRONTEND=noninteractive \
    ROS_DISTRO=humble \
    LANG=C.UTF-8 \
    LC_ALL=C.UTF-8

ARG ROS_DISTRO=humble

RUN apt-get update && apt-get install -y \
    python3-pip \
    ros-${ROS_DISTRO}-ros-base \
    python3-colcon-common-extensions \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Give the image the same user privilege as the host user
# Unique numbers for each group and user. 1000 is the first regular number
ARG UNAME="mumble_physical_runtime"
# Sets default value if docker build --build-arg UID=1000 is not provided.
# So, one caveat of this script is on Rpi, UID, GID have to be 1000.
ARG UID=1000
ARG GID=1000
RUN groupadd -f -g $GID $UNAME
RUN id -u $UNAME || useradd -m -u $UID -g $GID -s /bin/bash $UNAME
# RUN adduser --disabled-password --gecos '' ${UNAME}
RUN adduser ${UNAME} sudo
# adding UNAME to sudoers
RUN echo "${UNAME} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
USER $UNAME
# Env variables will persist across images
ARG WORKDIRECTORY="TO_GET_FROM_DOCKER_COMPOSE"
# mumble_physical_runtime/bin
ENV PATH="${WORKDIRECTORY}/src/bin:${PATH}"
WORKDIR ${WORKDIRECTORY}

RUN echo "source /opt/ros/humble/setup.bash" >> /home/$UNAME/.bashrc
CMD /bin/bash