visualize: false # The final result will be saved regardless
add_keyframes_only: true
# visualize_speedups: 10 # Must be integer
# fixed_camera_perception: false

kf_angle_thre: 0.52 #30 deg
kf_dist_thre:  1.0  #0.3m
keyframe_frame_gap: 10

nearest_distance_range: 0.3 # in meters
farthest_distance_range: 4.5 # in meters


# add_scan_leaf_size is used in scan matching, visualize_scan_leaf_size is a secondary filter for visualization
add_scan_leaf_size: 0.02
visualize_scan_leaf_size: 0.01
visualizer_spin_time: 5 #in ms