#######################################################################
# front end
#######################################################################
visualize: false # The final result will be saved regardless
kf_angle_thre: 0.52 #30 deg
kf_dist_thre:  1.0  #0.3m
keyframe_frame_gap: 10 # TODO

nearest_distance_range: 0.3 # in meters

# add_scan_leaf_size is used in scan matching, visualize_scan_leaf_size is a secondary filter for visualization
add_scan_leaf_size: 0.01
visualize_scan_leaf_size: 0.01
visualizer_spin_time: 5000 #5000 #in ms

#######################################################################
# IEKF Parameters
#######################################################################

iekf_kf_angle_thre: 0.26 #15 deg
iekf_kf_dist_thre:  1.0  #0.3m

#######################################################################
# Shared Parameters
#######################################################################

farthest_distance_range: 4.5 #4.5 # in meters

#######################################################################
# Inc NDT Scan Matching Parameters
#######################################################################

max_iterations: 20
opt_err_rejection_distance_sq: 9.0  #in meters
min_pts_in_voxel: 5
max_pts_in_voxel: 50000
eps: 1e-3
resolution: 3.0 # This could make a difference
max_voxel_number: 100000  # above which we pop the oldest voxel
consecutive_idx_check_range: 10 # [-range, +range] keyframes would be checked

#######################################################################
# Loop closure Parameters
#######################################################################

min_id_interval: 50       # Minimum ID difference between candidate keyframes
min_distance: 30.0       # Minimum distance between candidate frames
skip_id: 5              # Number of IDs to skip after selecting a candidate
ndt_score_th: 2.5       # NDT score threshold for valid loop closures
ground_z_val: 0.2 # Z value of the ground plane, which is used to filter out the ground points
loop_closure_submap_interval: 1 # Interval for submap generation from keyframes